name-template: "TaxSmart v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: 🚀 Features
    labels: [enhancement]
  - title: 🐛 Fixes
    labels: [bug]
  - title: 🛡️ Security
    labels: [security]
  - title: 🧰 Maintenance
    labels: [chore, deps]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES

  ## Upgrade notes
  - No breaking changes unless noted above.
