name: Bug report
description: Something not working as expected? Tell us.
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Clear steps, actual vs. expected.
    validations: { required: true }
  - type: input
    id: url
    attributes:
      label: Scenario link (if any)
      placeholder: https://taxapp.thesolutiondesk.ca/?p=BC&items=...
  - type: dropdown
    id: province
    attributes:
      label: Province / Territory
      options: [AB, BC, MB, NB, NL, NS, NT, NU, ON, PE, QC, SK, YT]
  - type: input
    id: ua
    attributes:
      label: Browser + OS
      placeholder: "Chrome 140 on Windows 10"
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Step-by-step so we can reproduce.
  - type: textarea
    id: logs
    attributes:
      label: Console logs / screenshots
