name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    name: CI / build-test
    runs-on: ubuntu-latest

    # Least-privilege for actions/checkout
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Test
        run: npm test -- --passWithNoTests

      - name: Build
        run: npm run build
